export const cities = [
  {
    id: "01",
    provinceName: "اردبيل",
    name: "اردبيل",
    provinceId: "24",
  },
  {
    id: "11",
    provinceName: "اردبيل",
    name: "اصلاندوز",
    provinceId: "24",
  },
  {
    id: "02",
    provinceName: "اردبيل",
    name: "بيله سوار",
    provinceId: "24",
  },
  {
    id: "06",
    provinceName: "اردبيل",
    name: "پارس آباد",
    provinceId: "24",
  },
  {
    id: "03",
    provinceName: "اردبيل",
    name: "خلخال",
    provinceId: "24",
  },
  {
    id: "10",
    provinceName: "اردبيل",
    name: "سرعين",
    provinceId: "24",
  },
  {
    id: "07",
    provinceName: "اردبيل",
    name: "كوثر",
    provinceId: "24",
  },
  {
    id: "05",
    provinceName: "اردبيل",
    name: "گرمی",
    provinceId: "24",
  },
  {
    id: "04",
    provinceName: "اردبيل",
    name: "مشگين شهر",
    provinceId: "24",
  },
  {
    id: "08",
    provinceName: "اردبيل",
    name: "نمين",
    provinceId: "24",
  },
  {
    id: "09",
    provinceName: "اردبيل",
    name: "نير",
    provinceId: "24",
  },
  {
    id: "01",
    provinceName: "اصفهان",
    name: "اردستان",
    provinceId: "10",
  },
  {
    id: "02",
    provinceName: "اصفهان",
    name: "اصفهان",
    provinceId: "10",
  },
  {
    id: "18",
    provinceName: "اصفهان",
    name: "آران وبيدگل",
    provinceId: "10",
  },
  {
    id: "22",
    provinceName: "اصفهان",
    name: "برخوار",
    provinceId: "10",
  },
  {
    id: "24",
    provinceName: "اصفهان",
    name: "بو يين و مياندشت",
    provinceId: "10",
  },
  {
    id: "19",
    provinceName: "اصفهان",
    name: "تيران وکرون",
    provinceId: "10",
  },
  {
    id: "20",
    provinceName: "اصفهان",
    name: "چادگان",
    provinceId: "10",
  },
  {
    id: "03",
    provinceName: "اصفهان",
    name: "خميني شهر",
    provinceId: "10",
  },
  {
    id: "04",
    provinceName: "اصفهان",
    name: "خوانسار",
    provinceId: "10",
  },
  {
    id: "23",
    provinceName: "اصفهان",
    name: "خور و بيابانک",
    provinceId: "10",
  },
  {
    id: "21",
    provinceName: "اصفهان",
    name: "دهاقان",
    provinceId: "10",
  },
  {
    id: "05",
    provinceName: "اصفهان",
    name: "سميرم",
    provinceId: "10",
  },
  {
    id: "16",
    provinceName: "اصفهان",
    name: "شاهين شهروميمه",
    provinceId: "10",
  },
  {
    id: "09",
    provinceName: "اصفهان",
    name: "شهرضا",
    provinceId: "10",
  },
  {
    id: "06",
    provinceName: "اصفهان",
    name: "فريدن",
    provinceId: "10",
  },
  {
    id: "07",
    provinceName: "اصفهان",
    name: "فريدونشهر",
    provinceId: "10",
  },
  {
    id: "08",
    provinceName: "اصفهان",
    name: "فلاورجان",
    provinceId: "10",
  },
  {
    id: "10",
    provinceName: "اصفهان",
    name: "کاشان",
    provinceId: "10",
  },
  {
    id: "11",
    provinceName: "اصفهان",
    name: "گلپايگان",
    provinceId: "10",
  },
  {
    id: "12",
    provinceName: "اصفهان",
    name: "لنجان",
    provinceId: "10",
  },
  {
    id: "17",
    provinceName: "اصفهان",
    name: "مبارکه",
    provinceId: "10",
  },
  {
    id: "13",
    provinceName: "اصفهان",
    name: "نايين",
    provinceId: "10",
  },
  {
    id: "14",
    provinceName: "اصفهان",
    name: "نجف آباد",
    provinceId: "10",
  },
  {
    id: "15",
    provinceName: "اصفهان",
    name: "نطنز",
    provinceId: "10",
  },
  {
    id: "05",
    provinceName: "البرز",
    name: "اشتهارد",
    provinceId: "30",
  },
  {
    id: "02",
    provinceName: "البرز",
    name: "ساوجبلاغ",
    provinceId: "30",
  },
  {
    id: "04",
    provinceName: "البرز",
    name: "طالقان",
    provinceId: "30",
  },
  {
    id: "06",
    provinceName: "البرز",
    name: "فرديس",
    provinceId: "30",
  },
  {
    id: "01",
    provinceName: "البرز",
    name: "کرج",
    provinceId: "30",
  },
  {
    id: "03",
    provinceName: "البرز",
    name: "نظرآباد",
    provinceId: "30",
  },
  {
    id: "01",
    provinceName: "ايلام",
    name: "ايلام",
    provinceId: "16",
  },
  {
    id: "07",
    provinceName: "ايلام",
    name: "ايوان",
    provinceId: "16",
  },
  {
    id: "06",
    provinceName: "ايلام",
    name: "آبدانان",
    provinceId: "16",
  },
  {
    id: "10",
    provinceName: "ايلام",
    name: "بدره",
    provinceId: "16",
  },
  {
    id: "04",
    provinceName: "ايلام",
    name: "چرداول",
    provinceId: "16",
  },
  {
    id: "02",
    provinceName: "ايلام",
    name: "دره شهر",
    provinceId: "16",
  },
  {
    id: "03",
    provinceName: "ايلام",
    name: "دهلران",
    provinceId: "16",
  },
  {
    id: "09",
    provinceName: "ايلام",
    name: "سيروان",
    provinceId: "16",
  },
  {
    id: "08",
    provinceName: "ايلام",
    name: "ملكشاهی",
    provinceId: "16",
  },
  {
    id: "05",
    provinceName: "ايلام",
    name: "مهران",
    provinceId: "16",
  },
  {
    id: "11",
    provinceName: "ايلام",
    name: "هلیلان",
    provinceId: "16",
  },
  {
    id: "22",
    provinceName: "آذربايجان شرقی",
    name: "اسکو",
    provinceId: "03",
  },
  {
    id: "02",
    provinceName: "آذربايجان شرقی",
    name: "اهر",
    provinceId: "03",
  },
  {
    id: "21",
    provinceName: "آذربايجان شرقی",
    name: "آذرشهر",
    provinceId: "03",
  },
  {
    id: "13",
    provinceName: "آذربايجان شرقی",
    name: "بستان آباد",
    provinceId: "03",
  },
  {
    id: "12",
    provinceName: "آذربايجان شرقی",
    name: "بناب",
    provinceId: "03",
  },
  {
    id: "03",
    provinceName: "آذربايجان شرقی",
    name: "تبريز",
    provinceId: "03",
  },
  {
    id: "19",
    provinceName: "آذربايجان شرقی",
    name: "جلفا",
    provinceId: "03",
  },
  {
    id: "23",
    provinceName: "آذربايجان شرقی",
    name: "چاراويماق",
    provinceId: "03",
  },
  {
    id: "26",
    provinceName: "آذربايجان شرقی",
    name: "خداآفرين",
    provinceId: "03",
  },
  {
    id: "05",
    provinceName: "آذربايجان شرقی",
    name: "سراب",
    provinceId: "03",
  },
  {
    id: "14",
    provinceName: "آذربايجان شرقی",
    name: "شبستر",
    provinceId: "03",
  },
  {
    id: "25",
    provinceName: "آذربايجان شرقی",
    name: "عجب شير",
    provinceId: "03",
  },
  {
    id: "15",
    provinceName: "آذربايجان شرقی",
    name: "کليبر",
    provinceId: "03",
  },
  {
    id: "06",
    provinceName: "آذربايجان شرقی",
    name: "مراغه",
    provinceId: "03",
  },
  {
    id: "07",
    provinceName: "آذربايجان شرقی",
    name: "مرند",
    provinceId: "03",
  },
  {
    id: "20",
    provinceName: "آذربايجان شرقی",
    name: "ملکان",
    provinceId: "03",
  },
  {
    id: "10",
    provinceName: "آذربايجان شرقی",
    name: "ميانه",
    provinceId: "03",
  },
  {
    id: "16",
    provinceName: "آذربايجان شرقی",
    name: "هريس",
    provinceId: "03",
  },
  {
    id: "11",
    provinceName: "آذربايجان شرقی",
    name: "هشترود",
    provinceId: "03",
  },
  {
    id: "27",
    provinceName: "آذربايجان شرقی",
    name: "هوراند",
    provinceId: "03",
  },
  {
    id: "24",
    provinceName: "آذربايجان شرقی",
    name: "ورزقان",
    provinceId: "03",
  },
  {
    id: "01",
    provinceName: "آذربايجان غربی",
    name: "اروميه",
    provinceId: "04",
  },
  {
    id: "13",
    provinceName: "آذربايجان غربی",
    name: "اشنويه",
    provinceId: "04",
  },
  {
    id: "10",
    provinceName: "آذربايجان غربی",
    name: "بوكان",
    provinceId: "04",
  },
  {
    id: "15",
    provinceName: "آذربايجان غربی",
    name: "پلدشت",
    provinceId: "04",
  },
  {
    id: "02",
    provinceName: "آذربايجان غربی",
    name: "پيرانشهر",
    provinceId: "04",
  },
  {
    id: "12",
    provinceName: "آذربايجان غربی",
    name: "تكاب",
    provinceId: "04",
  },
  {
    id: "14",
    provinceName: "آذربايجان غربی",
    name: "چالدران",
    provinceId: "04",
  },
  {
    id: "16",
    provinceName: "آذربايجان غربی",
    name: "چايپاره",
    provinceId: "04",
  },
  {
    id: "03",
    provinceName: "آذربايجان غربی",
    name: "خوی",
    provinceId: "04",
  },
  {
    id: "04",
    provinceName: "آذربايجان غربی",
    name: "سردشت",
    provinceId: "04",
  },
  {
    id: "05",
    provinceName: "آذربايجان غربی",
    name: "سلماس",
    provinceId: "04",
  },
  {
    id: "11",
    provinceName: "آذربايجان غربی",
    name: "شاهين دژ",
    provinceId: "04",
  },
  {
    id: "17",
    provinceName: "آذربايجان غربی",
    name: "شوط",
    provinceId: "04",
  },
  {
    id: "06",
    provinceName: "آذربايجان غربی",
    name: "ماكو",
    provinceId: "04",
  },
  {
    id: "07",
    provinceName: "آذربايجان غربی",
    name: "مهاباد",
    provinceId: "04",
  },
  {
    id: "08",
    provinceName: "آذربايجان غربی",
    name: "مياندوآب",
    provinceId: "04",
  },
  {
    id: "09",
    provinceName: "آذربايجان غربی",
    name: "نقده",
    provinceId: "04",
  },
  {
    id: "01",
    provinceName: "بوشهر",
    name: "بوشهر",
    provinceId: "18",
  },
  {
    id: "02",
    provinceName: "بوشهر",
    name: "تنگستان",
    provinceId: "18",
  },
  {
    id: "09",
    provinceName: "بوشهر",
    name: "جم",
    provinceId: "18",
  },
  {
    id: "03",
    provinceName: "بوشهر",
    name: "دشتستان",
    provinceId: "18",
  },
  {
    id: "04",
    provinceName: "بوشهر",
    name: "دشتی",
    provinceId: "18",
  },
  {
    id: "05",
    provinceName: "بوشهر",
    name: "دير",
    provinceId: "18",
  },
  {
    id: "08",
    provinceName: "بوشهر",
    name: "ديلم",
    provinceId: "18",
  },
  {
    id: "10",
    provinceName: "بوشهر",
    name: "عسلويه",
    provinceId: "18",
  },
  {
    id: "06",
    provinceName: "بوشهر",
    name: "كنگان",
    provinceId: "18",
  },
  {
    id: "07",
    provinceName: "بوشهر",
    name: "گناوه",
    provinceId: "18",
  },
  {
    id: "10",
    provinceName: "تهران",
    name: "اسلامشهر",
    provinceId: "23",
  },
  {
    id: "19",
    provinceName: "تهران",
    name: "بهارستان",
    provinceId: "23",
  },
  {
    id: "13",
    provinceName: "تهران",
    name: "پاكدشت",
    provinceId: "23",
  },
  {
    id: "20",
    provinceName: "تهران",
    name: "پرديس",
    provinceId: "23",
  },
  {
    id: "18",
    provinceName: "تهران",
    name: "پيشوا",
    provinceId: "23",
  },
  {
    id: "01",
    provinceName: "تهران",
    name: "تهران",
    provinceId: "23",
  },
  {
    id: "02",
    provinceName: "تهران",
    name: "دماوند",
    provinceId: "23",
  },
  {
    id: "12",
    provinceName: "تهران",
    name: "رباط کريم",
    provinceId: "23",
  },
  {
    id: "03",
    provinceName: "تهران",
    name: "ری",
    provinceId: "23",
  },
  {
    id: "04",
    provinceName: "تهران",
    name: "شميرانات",
    provinceId: "23",
  },
  {
    id: "09",
    provinceName: "تهران",
    name: "شهريار",
    provinceId: "23",
  },
  {
    id: "14",
    provinceName: "تهران",
    name: "فيروزكوه",
    provinceId: "23",
  },
  {
    id: "16",
    provinceName: "تهران",
    name: "قدس",
    provinceId: "23",
  },
  {
    id: "21",
    provinceName: "تهران",
    name: "قرچک",
    provinceId: "23",
  },
  {
    id: "17",
    provinceName: "تهران",
    name: "ملارد",
    provinceId: "23",
  },
  {
    id: "06",
    provinceName: "تهران",
    name: "ورامين",
    provinceId: "23",
  },
  {
    id: "05",
    provinceName: "چهارمحال وبختياری",
    name: "اردل",
    provinceId: "14",
  },
  {
    id: "01",
    provinceName: "چهارمحال وبختياری",
    name: "بروجن",
    provinceId: "14",
  },
  {
    id: "09",
    provinceName: "چهارمحال وبختياری",
    name: "بن",
    provinceId: "14",
  },
  {
    id: "10",
    provinceName: "چهارمحال وبختياری",
    name: "خانميرزا",
    provinceId: "14",
  },
  {
    id: "08",
    provinceName: "چهارمحال وبختياری",
    name: "سامان",
    provinceId: "14",
  },
  {
    id: "02",
    provinceName: "چهارمحال وبختياری",
    name: "شهرکرد",
    provinceId: "14",
  },
  {
    id: "03",
    provinceName: "چهارمحال وبختياری",
    name: "فارسان",
    provinceId: "14",
  },
  {
    id: "06",
    provinceName: "چهارمحال وبختياری",
    name: "کوهرنگ",
    provinceId: "14",
  },
  {
    id: "07",
    provinceName: "چهارمحال وبختياری",
    name: "کيار",
    provinceId: "14",
  },
  {
    id: "04",
    provinceName: "چهارمحال وبختياری",
    name: "لردگان",
    provinceId: "14",
  },
  {
    id: "08",
    provinceName: "خراسان جنوبی",
    name: "بشرويه",
    provinceId: "29",
  },
  {
    id: "01",
    provinceName: "خراسان جنوبی",
    name: "بيرجند",
    provinceId: "29",
  },
  {
    id: "10",
    provinceName: "خراسان جنوبی",
    name: "خوسف",
    provinceId: "29",
  },
  {
    id: "02",
    provinceName: "خراسان جنوبی",
    name: "درميان",
    provinceId: "29",
  },
  {
    id: "09",
    provinceName: "خراسان جنوبی",
    name: "زيرکوه",
    provinceId: "29",
  },
  {
    id: "06",
    provinceName: "خراسان جنوبی",
    name: "سرايان",
    provinceId: "29",
  },
  {
    id: "03",
    provinceName: "خراسان جنوبی",
    name: "سربيشه",
    provinceId: "29",
  },
  {
    id: "11",
    provinceName: "خراسان جنوبی",
    name: "طبس",
    provinceId: "29",
  },
  {
    id: "07",
    provinceName: "خراسان جنوبی",
    name: "فردوس",
    provinceId: "29",
  },
  {
    id: "04",
    provinceName: "خراسان جنوبی",
    name: "قائنات",
    provinceId: "29",
  },
  {
    id: "05",
    provinceName: "خراسان جنوبی",
    name: "نهبندان",
    provinceId: "29",
  },
  {
    id: "37",
    provinceName: "خراسان رضوی",
    name: "باخرز",
    provinceId: "09",
  },
  {
    id: "31",
    provinceName: "خراسان رضوی",
    name: "بجستان",
    provinceId: "09",
  },
  {
    id: "23",
    provinceName: "خراسان رضوی",
    name: "بردسكن",
    provinceId: "09",
  },
  {
    id: "32",
    provinceName: "خراسان رضوی",
    name: "بينالود",
    provinceId: "09",
  },
  {
    id: "04",
    provinceName: "خراسان رضوی",
    name: "تايباد",
    provinceId: "09",
  },
  {
    id: "06",
    provinceName: "خراسان رضوی",
    name: "تربت جام",
    provinceId: "09",
  },
  {
    id: "05",
    provinceName: "خراسان رضوی",
    name: "تربت حيدريه",
    provinceId: "09",
  },
  {
    id: "34",
    provinceName: "خراسان رضوی",
    name: "جغتای",
    provinceId: "09",
  },
  {
    id: "36",
    provinceName: "خراسان رضوی",
    name: "جوين",
    provinceId: "09",
  },
  {
    id: "18",
    provinceName: "خراسان رضوی",
    name: "چناران",
    provinceId: "09",
  },
  {
    id: "29",
    provinceName: "خراسان رضوی",
    name: "خليل آباد",
    provinceId: "09",
  },
  {
    id: "19",
    provinceName: "خراسان رضوی",
    name: "خواف",
    provinceId: "09",
  },
  {
    id: "38",
    provinceName: "خراسان رضوی",
    name: "خوشاب",
    provinceId: "09",
  },
  {
    id: "39",
    provinceName: "خراسان رضوی",
    name: "داورزن",
    provinceId: "09",
  },
  {
    id: "07",
    provinceName: "خراسان رضوی",
    name: "درگز",
    provinceId: "09",
  },
  {
    id: "27",
    provinceName: "خراسان رضوی",
    name: "رشتخوار",
    provinceId: "09",
  },
  {
    id: "35",
    provinceName: "خراسان رضوی",
    name: "زاوه",
    provinceId: "09",
  },
  {
    id: "08",
    provinceName: "خراسان رضوی",
    name: "سبزوار",
    provinceId: "09",
  },
  {
    id: "20",
    provinceName: "خراسان رضوی",
    name: "سرخس",
    provinceId: "09",
  },
  {
    id: "40",
    provinceName: "خراسان رضوی",
    name: "صالح آباد",
    provinceId: "09",
  },
  {
    id: "22",
    provinceName: "خراسان رضوی",
    name: "فريمان",
    provinceId: "09",
  },
  {
    id: "33",
    provinceName: "خراسان رضوی",
    name: "فيروزه",
    provinceId: "09",
  },
  {
    id: "13",
    provinceName: "خراسان رضوی",
    name: "قوچان",
    provinceId: "09",
  },
  {
    id: "14",
    provinceName: "خراسان رضوی",
    name: "كاشمر",
    provinceId: "09",
  },
  {
    id: "28",
    provinceName: "خراسان رضوی",
    name: "كلات",
    provinceId: "09",
  },
  {
    id: "41",
    provinceName: "خراسان رضوی",
    name: "کوهسرخ",
    provinceId: "09",
  },
  {
    id: "15",
    provinceName: "خراسان رضوی",
    name: "گناباد",
    provinceId: "09",
  },
  {
    id: "16",
    provinceName: "خراسان رضوی",
    name: "مشهد",
    provinceId: "09",
  },
  {
    id: "30",
    provinceName: "خراسان رضوی",
    name: "مه ولات",
    provinceId: "09",
  },
  {
    id: "17",
    provinceName: "خراسان رضوی",
    name: "نيشابور",
    provinceId: "09",
  },
  {
    id: "01",
    provinceName: "خراسان شمالی",
    name: "اسفراين",
    provinceId: "28",
  },
  {
    id: "02",
    provinceName: "خراسان شمالی",
    name: "بجنورد",
    provinceId: "28",
  },
  {
    id: "03",
    provinceName: "خراسان شمالی",
    name: "جاجرم",
    provinceId: "28",
  },
  {
    id: "08",
    provinceName: "خراسان شمالی",
    name: "راز و جرگلان",
    provinceId: "28",
  },
  {
    id: "04",
    provinceName: "خراسان شمالی",
    name: "شيروان",
    provinceId: "28",
  },
  {
    id: "05",
    provinceName: "خراسان شمالی",
    name: "فاروج",
    provinceId: "28",
  },
  {
    id: "07",
    provinceName: "خراسان شمالی",
    name: "گرمه",
    provinceId: "28",
  },
  {
    id: "06",
    provinceName: "خراسان شمالی",
    name: "مانه وسملقان",
    provinceId: "28",
  },
  {
    id: "16",
    provinceName: "خوزستان",
    name: "اميديه",
    provinceId: "06",
  },
  {
    id: "21",
    provinceName: "خوزستان",
    name: "انديکا",
    provinceId: "06",
  },
  {
    id: "02",
    provinceName: "خوزستان",
    name: "انديمشک",
    provinceId: "06",
  },
  {
    id: "03",
    provinceName: "خوزستان",
    name: "اهواز",
    provinceId: "06",
  },
  {
    id: "04",
    provinceName: "خوزستان",
    name: "ايذه",
    provinceId: "06",
  },
  {
    id: "01",
    provinceName: "خوزستان",
    name: "آبادان",
    provinceId: "06",
  },
  {
    id: "26",
    provinceName: "خوزستان",
    name: "آغاجاری",
    provinceId: "06",
  },
  {
    id: "15",
    provinceName: "خوزستان",
    name: "باغ ملک",
    provinceId: "06",
  },
  {
    id: "24",
    provinceName: "خوزستان",
    name: "باوی",
    provinceId: "06",
  },
  {
    id: "05",
    provinceName: "خوزستان",
    name: "بندرماهشهر",
    provinceId: "06",
  },
  {
    id: "06",
    provinceName: "خوزستان",
    name: "بهبهان",
    provinceId: "06",
  },
  {
    id: "25",
    provinceName: "خوزستان",
    name: "حميديه",
    provinceId: "06",
  },
  {
    id: "07",
    provinceName: "خوزستان",
    name: "خرمشهر",
    provinceId: "06",
  },
  {
    id: "08",
    provinceName: "خوزستان",
    name: "دزفول",
    provinceId: "06",
  },
  {
    id: "09",
    provinceName: "خوزستان",
    name: "دشت آزادگان",
    provinceId: "06",
  },
  {
    id: "19",
    provinceName: "خوزستان",
    name: "رامشير",
    provinceId: "06",
  },
  {
    id: "10",
    provinceName: "خوزستان",
    name: "رامهرمز",
    provinceId: "06",
  },
  {
    id: "11",
    provinceName: "خوزستان",
    name: "شادگان",
    provinceId: "06",
  },
  {
    id: "14",
    provinceName: "خوزستان",
    name: "شوش",
    provinceId: "06",
  },
  {
    id: "12",
    provinceName: "خوزستان",
    name: "شوشتر",
    provinceId: "06",
  },
  {
    id: "27",
    provinceName: "خوزستان",
    name: "کارون",
    provinceId: "06",
  },
  {
    id: "20",
    provinceName: "خوزستان",
    name: "گتوند",
    provinceId: "06",
  },
  {
    id: "17",
    provinceName: "خوزستان",
    name: "لالی",
    provinceId: "06",
  },
  {
    id: "13",
    provinceName: "خوزستان",
    name: "مسجدسليمان",
    provinceId: "06",
  },
  {
    id: "22",
    provinceName: "خوزستان",
    name: "هفتکل",
    provinceId: "06",
  },
  {
    id: "18",
    provinceName: "خوزستان",
    name: "هنديجان",
    provinceId: "06",
  },
  {
    id: "23",
    provinceName: "خوزستان",
    name: "هويزه",
    provinceId: "06",
  },
  {
    id: "01",
    provinceName: "زنجان",
    name: "ابهر",
    provinceId: "19",
  },
  {
    id: "06",
    provinceName: "زنجان",
    name: "ايجرود",
    provinceId: "19",
  },
  {
    id: "03",
    provinceName: "زنجان",
    name: "خدابنده",
    provinceId: "19",
  },
  {
    id: "07",
    provinceName: "زنجان",
    name: "خرمدره",
    provinceId: "19",
  },
  {
    id: "04",
    provinceName: "زنجان",
    name: "زنجان",
    provinceId: "19",
  },
  {
    id: "10",
    provinceName: "زنجان",
    name: "سلطانيه",
    provinceId: "19",
  },
  {
    id: "08",
    provinceName: "زنجان",
    name: "طارم",
    provinceId: "19",
  },
  {
    id: "09",
    provinceName: "زنجان",
    name: "ماهنشان",
    provinceId: "19",
  },
  {
    id: "06",
    provinceName: "سمنان",
    name: "آرادان",
    provinceId: "20",
  },
  {
    id: "01",
    provinceName: "سمنان",
    name: "دامغان",
    provinceId: "20",
  },
  {
    id: "08",
    provinceName: "سمنان",
    name: "سرخه",
    provinceId: "20",
  },
  {
    id: "02",
    provinceName: "سمنان",
    name: "سمنان",
    provinceId: "20",
  },
  {
    id: "03",
    provinceName: "سمنان",
    name: "شاهرود",
    provinceId: "20",
  },
  {
    id: "04",
    provinceName: "سمنان",
    name: "گرمسار",
    provinceId: "20",
  },
  {
    id: "05",
    provinceName: "سمنان",
    name: "مهدئ شهر",
    provinceId: "20",
  },
  {
    id: "07",
    provinceName: "سمنان",
    name: "ميامی",
    provinceId: "20",
  },
  {
    id: "01",
    provinceName: "سيستان وبلوچستان",
    name: "ايرانشهر",
    provinceId: "11",
  },
  {
    id: "20",
    provinceName: "سيستان وبلوچستان",
    name: "بمپور",
    provinceId: "11",
  },
  {
    id: "21",
    provinceName: "سيستان وبلوچستان",
    name: "تفتان",
    provinceId: "11",
  },
  {
    id: "02",
    provinceName: "سيستان وبلوچستان",
    name: "چاه بهار",
    provinceId: "11",
  },
  {
    id: "03",
    provinceName: "سيستان وبلوچستان",
    name: "خاش",
    provinceId: "11",
  },
  {
    id: "22",
    provinceName: "سيستان وبلوچستان",
    name: "دشتیاری",
    provinceId: "11",
  },
  {
    id: "12",
    provinceName: "سيستان وبلوچستان",
    name: "دلگان",
    provinceId: "11",
  },
  {
    id: "08",
    provinceName: "سيستان وبلوچستان",
    name: "راسک",
    provinceId: "11",
  },
  {
    id: "04",
    provinceName: "سيستان وبلوچستان",
    name: "زابل",
    provinceId: "11",
  },
  {
    id: "05",
    provinceName: "سيستان وبلوچستان",
    name: "زاهدان",
    provinceId: "11",
  },
  {
    id: "10",
    provinceName: "سيستان وبلوچستان",
    name: "زهک",
    provinceId: "11",
  },
  {
    id: "06",
    provinceName: "سيستان وبلوچستان",
    name: "سراوان",
    provinceId: "11",
  },
  {
    id: "23",
    provinceName: "سيستان وبلوچستان",
    name: "سرباز",
    provinceId: "11",
  },
  {
    id: "14",
    provinceName: "سيستان وبلوچستان",
    name: "سيب و سوران",
    provinceId: "11",
  },
  {
    id: "19",
    provinceName: "سيستان وبلوچستان",
    name: "فنوج",
    provinceId: "11",
  },
  {
    id: "18",
    provinceName: "سيستان وبلوچستان",
    name: "قصرقند",
    provinceId: "11",
  },
  {
    id: "09",
    provinceName: "سيستان وبلوچستان",
    name: "کنارک",
    provinceId: "11",
  },
  {
    id: "13",
    provinceName: "سيستان وبلوچستان",
    name: "مهرستان",
    provinceId: "11",
  },
  {
    id: "17",
    provinceName: "سيستان وبلوچستان",
    name: "ميرجاوه",
    provinceId: "11",
  },
  {
    id: "07",
    provinceName: "سيستان وبلوچستان",
    name: "نيک شهر",
    provinceId: "11",
  },
  {
    id: "15",
    provinceName: "سيستان وبلوچستان",
    name: "نيمروز",
    provinceId: "11",
  },
  {
    id: "16",
    provinceName: "سيستان وبلوچستان",
    name: "هامون",
    provinceId: "11",
  },
  {
    id: "11",
    provinceName: "سيستان وبلوچستان",
    name: "هيرمند",
    provinceId: "11",
  },
  {
    id: "17",
    provinceName: "فارس",
    name: "ارسنجان",
    provinceId: "07",
  },
  {
    id: "02",
    provinceName: "فارس",
    name: "استهبان",
    provinceId: "07",
  },
  {
    id: "03",
    provinceName: "فارس",
    name: "اقليد",
    provinceId: "07",
  },
  {
    id: "36",
    provinceName: "فارس",
    name: "اوز",
    provinceId: "07",
  },
  {
    id: "01",
    provinceName: "فارس",
    name: "آباده",
    provinceId: "07",
  },
  {
    id: "35",
    provinceName: "فارس",
    name: "بختگان",
    provinceId: "07",
  },
  {
    id: "16",
    provinceName: "فارس",
    name: "بوانات",
    provinceId: "07",
  },
  {
    id: "31",
    provinceName: "فارس",
    name: "بیضا",
    provinceId: "07",
  },
  {
    id: "23",
    provinceName: "فارس",
    name: "پاسارگاد",
    provinceId: "07",
  },
  {
    id: "04",
    provinceName: "فارس",
    name: "جهرم",
    provinceId: "07",
  },
  {
    id: "29",
    provinceName: "فارس",
    name: "خرامه",
    provinceId: "07",
  },
  {
    id: "18",
    provinceName: "فارس",
    name: "خرم بيد",
    provinceId: "07",
  },
  {
    id: "34",
    provinceName: "فارس",
    name: "خفر",
    provinceId: "07",
  },
  {
    id: "24",
    provinceName: "فارس",
    name: "خنج",
    provinceId: "07",
  },
  {
    id: "05",
    provinceName: "فارس",
    name: "داراب",
    provinceId: "07",
  },
  {
    id: "26",
    provinceName: "فارس",
    name: "رستم",
    provinceId: "07",
  },
  {
    id: "30",
    provinceName: "فارس",
    name: "زرقان",
    provinceId: "07",
  },
  {
    id: "19",
    provinceName: "فارس",
    name: "زرين دشت",
    provinceId: "07",
  },
  {
    id: "06",
    provinceName: "فارس",
    name: "سپيدان",
    provinceId: "07",
  },
  {
    id: "32",
    provinceName: "فارس",
    name: "سرچهان",
    provinceId: "07",
  },
  {
    id: "25",
    provinceName: "فارس",
    name: "سروستان",
    provinceId: "07",
  },
  {
    id: "07",
    provinceName: "فارس",
    name: "شيراز",
    provinceId: "07",
  },
  {
    id: "22",
    provinceName: "فارس",
    name: "فراشبند",
    provinceId: "07",
  },
  {
    id: "08",
    provinceName: "فارس",
    name: "فسا",
    provinceId: "07",
  },
  {
    id: "09",
    provinceName: "فارس",
    name: "فيروزآباد",
    provinceId: "07",
  },
  {
    id: "20",
    provinceName: "فارس",
    name: "قيروکارزين",
    provinceId: "07",
  },
  {
    id: "10",
    provinceName: "فارس",
    name: "کازرون",
    provinceId: "07",
  },
  {
    id: "28",
    provinceName: "فارس",
    name: "کوار",
    provinceId: "07",
  },
  {
    id: "33",
    provinceName: "فارس",
    name: "کوه چنار",
    provinceId: "07",
  },
  {
    id: "27",
    provinceName: "فارس",
    name: "گراش",
    provinceId: "07",
  },
  {
    id: "11",
    provinceName: "فارس",
    name: "لارستان",
    provinceId: "07",
  },
  {
    id: "15",
    provinceName: "فارس",
    name: "لامرد",
    provinceId: "07",
  },
  {
    id: "12",
    provinceName: "فارس",
    name: "مرودشت",
    provinceId: "07",
  },
  {
    id: "13",
    provinceName: "فارس",
    name: "ممسنی",
    provinceId: "07",
  },
  {
    id: "21",
    provinceName: "فارس",
    name: "مهر",
    provinceId: "07",
  },
  {
    id: "14",
    provinceName: "فارس",
    name: "ني ريز",
    provinceId: "07",
  },
  {
    id: "05",
    provinceName: "قزوين",
    name: "البرز",
    provinceId: "26",
  },
  {
    id: "04",
    provinceName: "قزوين",
    name: "آبيك",
    provinceId: "26",
  },
  {
    id: "06",
    provinceName: "قزوين",
    name: "آوج",
    provinceId: "26",
  },
  {
    id: "01",
    provinceName: "قزوين",
    name: "بوئين زهرا",
    provinceId: "26",
  },
  {
    id: "02",
    provinceName: "قزوين",
    name: "تاكستان",
    provinceId: "26",
  },
  {
    id: "03",
    provinceName: "قزوين",
    name: "قزوين",
    provinceId: "26",
  },
  {
    id: "01",
    provinceName: "قم",
    name: "قم",
    provinceId: "25",
  },
  {
    id: "01",
    provinceName: "كردستان",
    name: "بانه",
    provinceId: "12",
  },
  {
    id: "02",
    provinceName: "كردستان",
    name: "بيجار",
    provinceId: "12",
  },
  {
    id: "10",
    provinceName: "كردستان",
    name: "دهگلان",
    provinceId: "12",
  },
  {
    id: "07",
    provinceName: "كردستان",
    name: "ديواندره",
    provinceId: "12",
  },
  {
    id: "09",
    provinceName: "كردستان",
    name: "سروآباد",
    provinceId: "12",
  },
  {
    id: "03",
    provinceName: "كردستان",
    name: "سقز",
    provinceId: "12",
  },
  {
    id: "04",
    provinceName: "كردستان",
    name: "سنندج",
    provinceId: "12",
  },
  {
    id: "05",
    provinceName: "كردستان",
    name: "قروه",
    provinceId: "12",
  },
  {
    id: "08",
    provinceName: "كردستان",
    name: "كامياران",
    provinceId: "12",
  },
  {
    id: "06",
    provinceName: "كردستان",
    name: "مريوان",
    provinceId: "12",
  },
  {
    id: "23",
    provinceName: "كرمان",
    name: "ارزوئيه",
    provinceId: "08",
  },
  {
    id: "20",
    provinceName: "كرمان",
    name: "انار",
    provinceId: "08",
  },
  {
    id: "01",
    provinceName: "كرمان",
    name: "بافت",
    provinceId: "08",
  },
  {
    id: "10",
    provinceName: "كرمان",
    name: "بردسير",
    provinceId: "08",
  },
  {
    id: "02",
    provinceName: "كرمان",
    name: "بم",
    provinceId: "08",
  },
  {
    id: "03",
    provinceName: "كرمان",
    name: "جيرفت",
    provinceId: "08",
  },
  {
    id: "18",
    provinceName: "كرمان",
    name: "رابر",
    provinceId: "08",
  },
  {
    id: "11",
    provinceName: "كرمان",
    name: "راور",
    provinceId: "08",
  },
  {
    id: "04",
    provinceName: "كرمان",
    name: "رفسنجان",
    provinceId: "08",
  },
  {
    id: "15",
    provinceName: "كرمان",
    name: "رودبارجنوب",
    provinceId: "08",
  },
  {
    id: "17",
    provinceName: "كرمان",
    name: "ريگان",
    provinceId: "08",
  },
  {
    id: "05",
    provinceName: "كرمان",
    name: "زرند",
    provinceId: "08",
  },
  {
    id: "06",
    provinceName: "كرمان",
    name: "سيرجان",
    provinceId: "08",
  },
  {
    id: "07",
    provinceName: "كرمان",
    name: "شهربابك",
    provinceId: "08",
  },
  {
    id: "12",
    provinceName: "كرمان",
    name: "عنبرآباد",
    provinceId: "08",
  },
  {
    id: "22",
    provinceName: "كرمان",
    name: "فارياب",
    provinceId: "08",
  },
  {
    id: "19",
    provinceName: "كرمان",
    name: "فهرج",
    provinceId: "08",
  },
  {
    id: "16",
    provinceName: "كرمان",
    name: "قلعه گنج",
    provinceId: "08",
  },
  {
    id: "08",
    provinceName: "كرمان",
    name: "كرمان",
    provinceId: "08",
  },
  {
    id: "09",
    provinceName: "كرمان",
    name: "كهنوج",
    provinceId: "08",
  },
  {
    id: "14",
    provinceName: "كرمان",
    name: "كوهبنان",
    provinceId: "08",
  },
  {
    id: "13",
    provinceName: "كرمان",
    name: "منوجان",
    provinceId: "08",
  },
  {
    id: "21",
    provinceName: "كرمان",
    name: "نرماشير",
    provinceId: "08",
  },
  {
    id: "07",
    provinceName: "كهگيلويه وبويراحمد",
    name: "باشت",
    provinceId: "17",
  },
  {
    id: "05",
    provinceName: "كهگيلويه وبويراحمد",
    name: "بهمئی",
    provinceId: "17",
  },
  {
    id: "01",
    provinceName: "كهگيلويه وبويراحمد",
    name: "بويراحمد",
    provinceId: "17",
  },
  {
    id: "06",
    provinceName: "كهگيلويه وبويراحمد",
    name: "چرام",
    provinceId: "17",
  },
  {
    id: "04",
    provinceName: "كهگيلويه وبويراحمد",
    name: "دنا",
    provinceId: "17",
  },
  {
    id: "02",
    provinceName: "كهگيلويه وبويراحمد",
    name: "كهگيلويه",
    provinceId: "17",
  },
  {
    id: "03",
    provinceName: "كهگيلويه وبويراحمد",
    name: "گچساران",
    provinceId: "17",
  },
  {
    id: "08",
    provinceName: "كهگيلويه وبويراحمد",
    name: "لنده",
    provinceId: "17",
  },
  {
    id: "09",
    provinceName: "كهگيلويه وبويراحمد",
    name: "مارگون",
    provinceId: "17",
  },
  {
    id: "01",
    provinceName: "کرمانشاه",
    name: "اسلام آبادغرب",
    provinceId: "05",
  },
  {
    id: "03",
    provinceName: "کرمانشاه",
    name: "پاوه",
    provinceId: "05",
  },
  {
    id: "12",
    provinceName: "کرمانشاه",
    name: "ثلاث باباجانی",
    provinceId: "05",
  },
  {
    id: "09",
    provinceName: "کرمانشاه",
    name: "جوانرود",
    provinceId: "05",
  },
  {
    id: "13",
    provinceName: "کرمانشاه",
    name: "دالاهو",
    provinceId: "05",
  },
  {
    id: "14",
    provinceName: "کرمانشاه",
    name: "روانسر",
    provinceId: "05",
  },
  {
    id: "04",
    provinceName: "کرمانشاه",
    name: "سرپل ذهاب",
    provinceId: "05",
  },
  {
    id: "05",
    provinceName: "کرمانشاه",
    name: "سنقر",
    provinceId: "05",
  },
  {
    id: "10",
    provinceName: "کرمانشاه",
    name: "صحنه",
    provinceId: "05",
  },
  {
    id: "06",
    provinceName: "کرمانشاه",
    name: "قصرشيرين",
    provinceId: "05",
  },
  {
    id: "02",
    provinceName: "کرمانشاه",
    name: "کرمانشاه",
    provinceId: "05",
  },
  {
    id: "07",
    provinceName: "کرمانشاه",
    name: "کنگاور",
    provinceId: "05",
  },
  {
    id: "08",
    provinceName: "کرمانشاه",
    name: "گيلانغرب",
    provinceId: "05",
  },
  {
    id: "11",
    provinceName: "کرمانشاه",
    name: "هرسين",
    provinceId: "05",
  },
  {
    id: "10",
    provinceName: "گلستان",
    name: "آزادشهر",
    provinceId: "27",
  },
  {
    id: "08",
    provinceName: "گلستان",
    name: "آق قلا",
    provinceId: "27",
  },
  {
    id: "01",
    provinceName: "گلستان",
    name: "بندرگز",
    provinceId: "27",
  },
  {
    id: "02",
    provinceName: "گلستان",
    name: "تركمن",
    provinceId: "27",
  },
  {
    id: "11",
    provinceName: "گلستان",
    name: "راميان",
    provinceId: "27",
  },
  {
    id: "03",
    provinceName: "گلستان",
    name: "علي آباد کتول",
    provinceId: "27",
  },
  {
    id: "04",
    provinceName: "گلستان",
    name: "كردكوی",
    provinceId: "27",
  },
  {
    id: "09",
    provinceName: "گلستان",
    name: "كلاله",
    provinceId: "27",
  },
  {
    id: "14",
    provinceName: "گلستان",
    name: "گاليكش",
    provinceId: "27",
  },
  {
    id: "05",
    provinceName: "گلستان",
    name: "گرگان",
    provinceId: "27",
  },
  {
    id: "13",
    provinceName: "گلستان",
    name: "گميشان",
    provinceId: "27",
  },
  {
    id: "06",
    provinceName: "گلستان",
    name: "گنبدكاووس",
    provinceId: "27",
  },
  {
    id: "12",
    provinceName: "گلستان",
    name: "مراوه تپه",
    provinceId: "27",
  },
  {
    id: "07",
    provinceName: "گلستان",
    name: "مينودشت",
    provinceId: "27",
  },
  {
    id: "13",
    provinceName: "گيلان",
    name: "املش",
    provinceId: "01",
  },
  {
    id: "01",
    provinceName: "گيلان",
    name: "آستارا",
    provinceId: "01",
  },
  {
    id: "02",
    provinceName: "گيلان",
    name: "آستانه اشرفيه",
    provinceId: "01",
  },
  {
    id: "03",
    provinceName: "گيلان",
    name: "بندرانزلی",
    provinceId: "01",
  },
  {
    id: "05",
    provinceName: "گيلان",
    name: "رشت",
    provinceId: "01",
  },
  {
    id: "14",
    provinceName: "گيلان",
    name: "رضوانشهر",
    provinceId: "01",
  },
  {
    id: "06",
    provinceName: "گيلان",
    name: "رودبار",
    provinceId: "01",
  },
  {
    id: "07",
    provinceName: "گيلان",
    name: "رودسر",
    provinceId: "01",
  },
  {
    id: "15",
    provinceName: "گيلان",
    name: "سياهكل",
    provinceId: "01",
  },
  {
    id: "12",
    provinceName: "گيلان",
    name: "شفت",
    provinceId: "01",
  },
  {
    id: "08",
    provinceName: "گيلان",
    name: "صومعه سرا",
    provinceId: "01",
  },
  {
    id: "04",
    provinceName: "گيلان",
    name: "طوالش",
    provinceId: "01",
  },
  {
    id: "09",
    provinceName: "گيلان",
    name: "فومن",
    provinceId: "01",
  },
  {
    id: "11",
    provinceName: "گيلان",
    name: "لاهيجان",
    provinceId: "01",
  },
  {
    id: "10",
    provinceName: "گيلان",
    name: "لنگرود",
    provinceId: "01",
  },
  {
    id: "16",
    provinceName: "گيلان",
    name: "ماسال",
    provinceId: "01",
  },
  {
    id: "07",
    provinceName: "لرستان",
    name: "ازنا",
    provinceId: "15",
  },
  {
    id: "01",
    provinceName: "لرستان",
    name: "اليگودرز",
    provinceId: "15",
  },
  {
    id: "02",
    provinceName: "لرستان",
    name: "بروجرد",
    provinceId: "15",
  },
  {
    id: "08",
    provinceName: "لرستان",
    name: "پلدختر",
    provinceId: "15",
  },
  {
    id: "10",
    provinceName: "لرستان",
    name: "چگنی",
    provinceId: "15",
  },
  {
    id: "03",
    provinceName: "لرستان",
    name: "خرم آباد",
    provinceId: "15",
  },
  {
    id: "04",
    provinceName: "لرستان",
    name: "دلفان",
    provinceId: "15",
  },
  {
    id: "05",
    provinceName: "لرستان",
    name: "دورود",
    provinceId: "15",
  },
  {
    id: "11",
    provinceName: "لرستان",
    name: "رومشکان",
    provinceId: "15",
  },
  {
    id: "09",
    provinceName: "لرستان",
    name: "سلسله",
    provinceId: "15",
  },
  {
    id: "06",
    provinceName: "لرستان",
    name: "کوهدشت",
    provinceId: "15",
  },
  {
    id: "01",
    provinceName: "مازندران",
    name: "آمل",
    provinceId: "02",
  },
  {
    id: "02",
    provinceName: "مازندران",
    name: "بابل",
    provinceId: "02",
  },
  {
    id: "16",
    provinceName: "مازندران",
    name: "بابلسر",
    provinceId: "02",
  },
  {
    id: "04",
    provinceName: "مازندران",
    name: "بهشهر",
    provinceId: "02",
  },
  {
    id: "05",
    provinceName: "مازندران",
    name: "تنكابن",
    provinceId: "02",
  },
  {
    id: "21",
    provinceName: "مازندران",
    name: "جويبار",
    provinceId: "02",
  },
  {
    id: "20",
    provinceName: "مازندران",
    name: "چالوس",
    provinceId: "02",
  },
  {
    id: "06",
    provinceName: "مازندران",
    name: "رامسر",
    provinceId: "02",
  },
  {
    id: "07",
    provinceName: "مازندران",
    name: "ساری",
    provinceId: "02",
  },
  {
    id: "08",
    provinceName: "مازندران",
    name: "سوادكوه",
    provinceId: "02",
  },
  {
    id: "27",
    provinceName: "مازندران",
    name: "سوادکوه شمالی",
    provinceId: "02",
  },
  {
    id: "26",
    provinceName: "مازندران",
    name: "سيمرغ",
    provinceId: "02",
  },
  {
    id: "24",
    provinceName: "مازندران",
    name: "عباس آباد",
    provinceId: "02",
  },
  {
    id: "23",
    provinceName: "مازندران",
    name: "فريدونكنار",
    provinceId: "02",
  },
  {
    id: "10",
    provinceName: "مازندران",
    name: "قائم شهر",
    provinceId: "02",
  },
  {
    id: "28",
    provinceName: "مازندران",
    name: "کلاردشت",
    provinceId: "02",
  },
  {
    id: "22",
    provinceName: "مازندران",
    name: "گلوگاه",
    provinceId: "02",
  },
  {
    id: "18",
    provinceName: "مازندران",
    name: "محمودآباد",
    provinceId: "02",
  },
  {
    id: "25",
    provinceName: "مازندران",
    name: "مياندورود",
    provinceId: "02",
  },
  {
    id: "19",
    provinceName: "مازندران",
    name: "نكا",
    provinceId: "02",
  },
  {
    id: "14",
    provinceName: "مازندران",
    name: "نور",
    provinceId: "02",
  },
  {
    id: "15",
    provinceName: "مازندران",
    name: "نوشهر",
    provinceId: "02",
  },
  {
    id: "01",
    provinceName: "مرکزی",
    name: "اراک",
    provinceId: "00",
  },
  {
    id: "02",
    provinceName: "مرکزی",
    name: "آشتيان",
    provinceId: "00",
  },
  {
    id: "03",
    provinceName: "مرکزی",
    name: "تفرش",
    provinceId: "00",
  },
  {
    id: "04",
    provinceName: "مرکزی",
    name: "خمين",
    provinceId: "00",
  },
  {
    id: "12",
    provinceName: "مرکزی",
    name: "خنداب",
    provinceId: "00",
  },
  {
    id: "05",
    provinceName: "مرکزی",
    name: "دليجان",
    provinceId: "00",
  },
  {
    id: "10",
    provinceName: "مرکزی",
    name: "زرنديه",
    provinceId: "00",
  },
  {
    id: "06",
    provinceName: "مرکزی",
    name: "ساوه",
    provinceId: "00",
  },
  {
    id: "07",
    provinceName: "مرکزی",
    name: "شازند",
    provinceId: "00",
  },
  {
    id: "13",
    provinceName: "مرکزی",
    name: "فراهان",
    provinceId: "00",
  },
  {
    id: "11",
    provinceName: "مرکزی",
    name: "کميجان",
    provinceId: "00",
  },
  {
    id: "09",
    provinceName: "مرکزی",
    name: "محلات",
    provinceId: "00",
  },
  {
    id: "01",
    provinceName: "هرمزگان",
    name: "ابوموسی",
    provinceId: "22",
  },
  {
    id: "09",
    provinceName: "هرمزگان",
    name: "بستك",
    provinceId: "22",
  },
  {
    id: "13",
    provinceName: "هرمزگان",
    name: "بشاگرد",
    provinceId: "22",
  },
  {
    id: "02",
    provinceName: "هرمزگان",
    name: "بندرعباس",
    provinceId: "22",
  },
  {
    id: "03",
    provinceName: "هرمزگان",
    name: "بندرلنگه",
    provinceId: "22",
  },
  {
    id: "11",
    provinceName: "هرمزگان",
    name: "پارسيان",
    provinceId: "22",
  },
  {
    id: "06",
    provinceName: "هرمزگان",
    name: "جاسك",
    provinceId: "22",
  },
  {
    id: "08",
    provinceName: "هرمزگان",
    name: "حاجي اباد",
    provinceId: "22",
  },
  {
    id: "10",
    provinceName: "هرمزگان",
    name: "خمير",
    provinceId: "22",
  },
  {
    id: "07",
    provinceName: "هرمزگان",
    name: "رودان",
    provinceId: "22",
  },
  {
    id: "12",
    provinceName: "هرمزگان",
    name: "سيريك",
    provinceId: "22",
  },
  {
    id: "04",
    provinceName: "هرمزگان",
    name: "قشم",
    provinceId: "22",
  },
  {
    id: "05",
    provinceName: "هرمزگان",
    name: "ميناب",
    provinceId: "22",
  },
  {
    id: "06",
    provinceName: "همدان",
    name: "اسدآباد",
    provinceId: "13",
  },
  {
    id: "07",
    provinceName: "همدان",
    name: "بهار",
    provinceId: "13",
  },
  {
    id: "01",
    provinceName: "همدان",
    name: "تويسركان",
    provinceId: "13",
  },
  {
    id: "10",
    provinceName: "همدان",
    name: "درگزین",
    provinceId: "13",
  },
  {
    id: "08",
    provinceName: "همدان",
    name: "رزن",
    provinceId: "13",
  },
  {
    id: "09",
    provinceName: "همدان",
    name: "فامنين",
    provinceId: "13",
  },
  {
    id: "05",
    provinceName: "همدان",
    name: "كبودرآهنگ",
    provinceId: "13",
  },
  {
    id: "02",
    provinceName: "همدان",
    name: "ملاير",
    provinceId: "13",
  },
  {
    id: "03",
    provinceName: "همدان",
    name: "نهاوند",
    provinceId: "13",
  },
  {
    id: "04",
    provinceName: "همدان",
    name: "همدان",
    provinceId: "13",
  },
  {
    id: "07",
    provinceName: "يزد",
    name: "ابركوه",
    provinceId: "21",
  },
  {
    id: "01",
    provinceName: "يزد",
    name: "اردكان",
    provinceId: "21",
  },
  {
    id: "08",
    provinceName: "يزد",
    name: "اشکذر",
    provinceId: "21",
  },
  {
    id: "02",
    provinceName: "يزد",
    name: "بافق",
    provinceId: "21",
  },
  {
    id: "11",
    provinceName: "يزد",
    name: "بهاباد",
    provinceId: "21",
  },
  {
    id: "03",
    provinceName: "يزد",
    name: "تفت",
    provinceId: "21",
  },
  {
    id: "09",
    provinceName: "يزد",
    name: "خاتم",
    provinceId: "21",
  },
  {
    id: "04",
    provinceName: "يزد",
    name: "مهريز",
    provinceId: "21",
  },
  {
    id: "06",
    provinceName: "يزد",
    name: "ميبد",
    provinceId: "21",
  },
  {
    id: "05",
    provinceName: "يزد",
    name: "يزد",
    provinceId: "21",
  },
];
